# Usage:
# ansible-playbook \
#   -i $MUSIC_HOST, \
#   --extra-vars \
#    "hostname=$MUSIC_HOST \
#    wifi_password=$WIFI_PASS \
#    google_app_password=$GOOGLE_PASS \
#    media_username=$MEDIA_USERNAME \
#    media_password=$MEDIA_PASSWORD" \
# music_server.yml


---
- name: Music Server
  hosts: all
  become_user: root
  roles:
    - common
    - ouimeaux
    - mopidy
