---
- name: Install packages
  become: yes
  package:
    name: "{{ item }}"
    state: latest
  with_items: "{{ base_packages }}"

- name: Install pip
  become: yes
  easy_install:
    name: pip
    state: latest
